--role(角色表)
INSERT INTO "SCOTT"."ROLE" (ROLE_ID, ROLE_NAME) VALUES ('1', '管理员');
INSERT INTO "SCOTT"."ROLE" (ROLE_ID, ROLE_NAME) VALUES ('2', '店家');
INSERT INTO "SCOTT"."ROLE" (ROLE_ID, ROLE_NAME) VALUES ('3', '旅客');
commit;

--room_type(房间类型表)
INSERT INTO "SCOTT"."ROOM_TYPE" (ROOM_TYPE_ID, ROOM_TYPE_NAME, ROOM_TYPE_STANDARD, ROON_TYPE_BED_NUMBER) VALUES ('1', '标间', '标准', '2');
INSERT INTO "SCOTT"."ROOM_TYPE" (ROOM_TYPE_ID, ROOM_TYPE_NAME, ROOM_TYPE_STANDARD, ROON_TYPE_BED_NUMBER) VALUES ('2', '单间', '标准', '1');
INSERT INTO "SCOTT"."ROOM_TYPE" (ROOM_TYPE_ID, ROOM_TYPE_NAME, ROOM_TYPE_STANDARD, ROON_TYPE_BED_NUMBER) VALUES ('3', '套间', '标准', '4');
INSERT INTO "SCOTT"."ROOM_TYPE" (ROOM_TYPE_ID, ROOM_TYPE_NAME, ROOM_TYPE_STANDARD, ROON_TYPE_BED_NUMBER) VALUES ('4', '大床房', '标准', '2');
INSERT INTO "SCOTT"."ROOM_TYPE" (ROOM_TYPE_ID, ROOM_TYPE_NAME, ROOM_TYPE_STANDARD, ROON_TYPE_BED_NUMBER) VALUES ('5', '钟点房', '标准', '2');
INSERT INTO "SCOTT"."ROOM_TYPE" (ROOM_TYPE_ID, ROOM_TYPE_NAME, ROOM_TYPE_STANDARD, ROON_TYPE_BED_NUMBER) VALUES ('6', '总统套房', '标准', '2');
commit;